[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "my-project-229056"
entrypoint = "hello.py"

[branding]
name = "HarambeHombre - Titanic Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.my_dataset]
type = "csv"
path = "data/train.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 